In [1]:
import torch

In [11]:
x=torch.ones(5)
y=torch.zeros(3)
w=torch.randn(5,3,requires_grad=True)
b=torch.randn(3,requires_grad=True)
z=torch.matmul(x,w)+b
loss=torch.nn.functional.binary_cross_entropy_with_logits(z,y)
print(f"x:{x}")
print(f"w:{w}")
print(f"b:{b}")

x:tensor([1., 1., 1., 1., 1.])
w:tensor([[ 1.0741e+00, -4.7511e-01, -5.2156e-01],
        [ 2.5380e-01, -1.6641e+00, -3.1811e-01],
        [-4.1559e-01, -5.7408e-04,  4.7116e-01],
        [ 5.6878e-01, -1.5407e+00,  8.5832e-01],
        [ 1.8967e+00, -1.7787e+00, -3.9600e-01]], requires_grad=True)
b:tensor([-1.1554,  1.3943,  0.0519], requires_grad=True)


In [12]:
print(f"Gradient function for z = {z.grad_fn}")
print(f"Gradient function for loss = {loss.grad_fn}")

Gradient function for z = <AddBackward0 object at 0x0000014D7F5408E0>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x0000014D7F5403A0>


In [13]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[0.3007, 0.0056, 0.1788],
        [0.3007, 0.0056, 0.1788],
        [0.3007, 0.0056, 0.1788],
        [0.3007, 0.0056, 0.1788],
        [0.3007, 0.0056, 0.1788]])
tensor([0.3007, 0.0056, 0.1788])


In [14]:
z = torch.matmul(x, w)+b
print(z.requires_grad)

with torch.no_grad():
    z = torch.matmul(x, w)+b
print(z.requires_grad)

True
False


In [16]:
# detach函数用于禁止梯度
z = torch.matmul(x, w)+b
z_det = z.detach()
print(z_det.requires_grad)

False


In [25]:
inp=torch.eye(4,5, requires_grad=True)
out=(inp+1).pow(2).T
print(f"out:{out}")
# 必须注明梯度的形状
out.backward(torch.ones_like(out), retain_graph=True)
print(f"First call\n{inp.grad}")
out.backward(torch.ones_like(out), retain_graph=True)
print(f"\nSecond call\n{inp.grad}")
inp.grad.zero_()
out.backward(torch.ones_like(out), retain_graph=True)
print(f"\nCall after zeroing gradients\n{inp.grad}")

out:tensor([[4., 1., 1., 1.],
        [1., 4., 1., 1.],
        [1., 1., 4., 1.],
        [1., 1., 1., 4.],
        [1., 1., 1., 1.]], grad_fn=<PermuteBackward0>)
First call
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])

Second call
tensor([[8., 4., 4., 4., 4.],
        [4., 8., 4., 4., 4.],
        [4., 4., 8., 4., 4.],
        [4., 4., 4., 8., 4.]])

Call after zeroing gradients
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.]])
