In [2]:
import torch

a=torch.tensor([1,2,3,4,5,6])
a.resize_(2,3,4)
a

tensor([[[1, 2, 3, 4],
         [5, 6, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]])

In [17]:
a=[torch.tensor([[0.7,0.3],[0.2,0.8]]),torch.tensor([[0.5,0.9],[0.5,0.5]])]
stack1=torch.stack(a)
b=torch.tensor([[0.1,0.9],[0.2,0.7]])
stack2=torch.cat((stack1,b[None]), dim=0)
stack2.shape

torch.Size([3, 2, 2])

In [33]:
import torch

# 创建一个张量
tensor = torch.tensor([[[1], [2], [3]]])

print("原始张量：")
print(tensor)
print(tensor.shape)

# 指定要移除的维度
squeezed_tensor_dim0 = torch.squeeze(tensor, dim=0)
squeezed_tensor_dim2 = torch.squeeze(tensor, dim=2)

print("移除第0维度后的张量：")
print(squeezed_tensor_dim0)
print(squeezed_tensor_dim0.shape)

print("移除第2维度后的张量：")
print(squeezed_tensor_dim2)
print(squeezed_tensor_dim2.shape)

原始张量：
tensor([[[1],
         [2],
         [3]]])
torch.Size([1, 3, 1])
移除第0维度后的张量：
tensor([[1],
        [2],
        [3]])
torch.Size([3, 1])
移除第2维度后的张量：
tensor([[1, 2, 3]])
torch.Size([1, 3])


In [40]:
x=torch.rand(2,1,3)
x=torch.squeeze(x, dim=1)
x.shape

torch.Size([2, 3])

In [44]:
x=torch.tensor(range(0,6)).view(3,1,2)
x

tensor([[[0, 1]],

        [[2, 3]],

        [[4, 5]]])

In [51]:
a=torch.rand(4,4)
print(a)
a=torch.triu(a,diagonal=0)
print(a)

tensor([[0.4886, 0.2592, 0.3424, 0.5356],
        [0.3580, 0.6022, 0.7804, 0.1933],
        [0.6373, 0.8072, 0.4053, 0.3726],
        [0.2126, 0.0659, 0.9828, 0.1160]])
tensor([[0.4886, 0.2592, 0.3424, 0.5356],
        [0.0000, 0.6022, 0.7804, 0.1933],
        [0.0000, 0.0000, 0.4053, 0.3726],
        [0.0000, 0.0000, 0.0000, 0.1160]])


In [62]:
x=torch.tensor([[2.0,9.0],[1.0,2.0]], requires_grad=True)
y=x[0]**2
y.backward()
print(x.grad)

RuntimeError: grad can be implicitly created only for scalar outputs